Add types to maps to make mypy happy
By adding a type (which was already defined) to the maps, we resolved
these mypy errors:

src\handlermaps\status.py:69: error: Dict entry 0 has incompatible type
"object": "Any"; expected "str": "Any"  [dict-item]
src\handlermaps\status.py:69: error: "object" not callable  [operator]